// Results of running scraper.js
const varNames = {
    'Gold, London A.M. Fixing': 'LBMA/GOLD',
    'Gold, London P.M. Fixing': 'BMA/GOLD',
    'Gold, World Gold Council': 'WGC/GOLD_DAILY_USD',
    'Gold, Bundesbank': 'BUNDESBANK/BBK01_WT5511',
    'Gold, COMEX Gold Futures': 'CHRIS/CME_GC1',
    'Gold, Shanghai Gold Futures': 'SHFE/AUV2013',
    'Gold, World Bank': 'WORLDBANK/WLD_GOLD',
    'Silver, London fixing, USD equivalent': 'LBMA/SILVER',
    'Silver, Shanghai Silver Futures': 'SHFE/AGV2013',
    'Silver, COMEX Silver Futures': 'CHRIS/CME_SI1',
    'Silver, World Bank': 'WORLDBANK/WLD_SILVER',
    'Platinum, Johnson Mathey London': 'JOHNMATT/PLAT',
    'Platinum, NYMEX Platinum Futures': 'CHRIS/CME_PL1',
    'Palladium, Johnson Mathey London': 'JOHNMATT/PALL',
    'Palladium, NYMEX Palladium Futures': 'CHRIS/CME_PA1',
    'Iridium': 'JOHNMATT/IRID',
    'Rhodium': 'JOHNMATT/RHOD',
    'Ruthenium': 'JOHNMATT/RUTH',
    'Aluminum, LME': 'LME/PR_AL',
    'Aluminum, ODA': 'ODA/PALUM_USD',
    'Shanghai Aluminum Futures': 'SHFE/ALV2013',
    'Cobalt, LME': 'LME/PR_CO',
    'Copper, LME': 'LME/PR_CU',
    'Copper, ODA': 'ODA/PCOPP_USD',
    'Copper Futures': 'CHRIS/CME_HG1',
    'Shanghai Copper Futures': 'SHFE/CUV2013',
    'Iron Ore, Tianjin (ODA)': 'ODA/PIORECR_USD',
    'Lead, LME': 'LME/PR_PB',
    'Lead, ODA': 'ODA/PLEAD_USD',
    'Shanghai Lead Futures': 'SHFE/PBV2013',
    'Molybdenum, LME': 'LME/PR_MO',
    'Nickel, LME': 'LME/PR_NI',
    'Nickel, ODA': 'ODA/PNICK_USD',
    'Steel Billet, LME': 'LME/PR_FM',
    'Steel Wire': 'WORLDBANK/WLD_STL_JP_WIROD',
    'Shanghai Steel Rebar Futures': 'SHFE/RBV2013',
    'Shanghai Steel Wire Futures': 'SHFE/WRV2013',
    'Tin, LME': 'LME/PR_TN',
    'Tin, ODA': 'ODA/PTIN_USD',
    'Zinc, LME': 'LME/PR_ZI',
    'Zinc, ODA': 'ODA/PZINC_USD',
    'Shanghai Zinc Futures': 'SHFE/ZNV2013',
    'Barley, Western Canada (ODA)': 'ODA/PBARL_USD',
    'Barley, Western Canada (WB)': 'WORLDBANK/WLD_BARLEY',
    'Corn, Top Flight Grain Co-op': 'TFGRAIN/CORN',
    'Corn, CBOT Corn Futures': 'CHRIS/CME_C1',
    'Corn, U.S. Gulf Imports': 'WORLDBANK/WLD_MAIZE',
    'Oats, CBOT Oats Futures': 'CHRIS/CME_O1',
    'Rice, Thailand (ODA)': 'ODA/PRICENPQ_USD',
    'Rice, CBOT Rice Futures': 'CHRIS/CME_RR1',
    'Rice, Top Flight Grain Co-op': 'TFGRAIN/SOYBEANS',
    'Soybean, CBOT Soybean Futures': 'CHRIS/CME_S1',
    'Soybean, CBOT Soybean Meal Futures': 'CHRIS/CME_SM1',
    'Wheat, Soybean Oil': 'WORLDBANK/WLD_SOYBEAN_OIL',
    'Wheat, CBOT Soybean Oil Futures': 'CHRIS/CME_BO1',
    'Wheat, Gulf of Mexico': 'ODA/PWHEAMT_USD',
    'Wheat, CBOT Wheat Futures': 'CHRIS/CME_W1',
    'Dairy, CME Milk Futures': 'CHRIS/CME_DA1',
    'Cattle, Beef (ODA)': 'ODA/PBEEF_USD',
    'Cattle, CME Live Cattle Futures': 'CHRIS/CME_LC1',
    'Cattle, CME Feeder Cattle Futures': 'CHRIS/CME_FC1',
    'Cattle, Hides, Chicago (ODA)': 'ODA/PHIDE_USD',
    'Poultry, Chicken, Georgia (ODA)': 'ODA/PPOULT_USD',
    'Pork, Pork, Chicago (ODA)': 'ODA/PPORK_USD',
    'Pork, CME Lean Hog Futures': 'CHRIS/CME_LN1',
    'Fats, Lamb': 'ODA/PLAMB_USD',
    'Wool': 'ODA/PWOOLC_USD',
    'Salmon': 'ODA/PSALM_USD',
    'Shrimp': 'ODA/PSHRI_USD',
    'Fishmeal': 'ODA/PFISH_USD',
    'NYMEX RBOB Gasoline Futures': 'CHRIS/CME_RB1',
    'NYMEX Crude Oil Futures': 'CHRIS/CME_CL1',
    'ICE Brent Crude Oil Futures': 'CHRIS/ICE_B1',
    'U.S. Landed Costs of Canadian Light Sour Blend Crude Oil': 'DOE/I19263000008',
    'Los Angeles Reformulated RBOB Regular Gasoline Spot': 'DOE/EER_EPMRR_PF4_Y05LA_DPG',
    'WTI Crude Oil Spot Cushing, OK FOB': 'DOE/RWTC',
    'Europe Brent Crude Oil Spot FOB': 'DOE/RBRTE',
    'U.S. FOB Costs of Non-OPEC Countries Crude Oil': 'DOE/I070000004',
    'U.S. FOB Costs of OPEC Countries Crude Oil': 'DOE/I060000004',
    'Crude Oils from 1861': 'BRP/CRUDE_OIL_PRICES',
    'OPEC Reference Basket': 'OPEC/ORB',
    'Dubai Crude Oil': 'ODA/POILDUB_USD',
    'Blended Crude Oil': 'ODA/POILAPSP_USD',
    'WTI Crude Oil': 'ODA/POILWTI_USD',
    'Brent Crude Oil': 'ODA/POILBRE_USD',
    'Europe & Central Asia (all income levels): Pump for gasoline (US$ per liter)': 'WORLDBANK/ECS_EP_PMP_SGAS_CD',
    'US Midgrade Conventional Gas': 'FRED/GASMIDCOVW',
    'Conventional Gasolines: New York Harbor, Regular': 'FRED/DGASNYH',
    'US Regular Conventional Gas': 'FRED/GASREGCOVW',
    'Conventional Gasolines: U.S. Gulf Coast, Regular': 'FRED/DGASUSGULF',
    'Consumer Index for All Urban Consumers: Gasoline (all types)': 'FRED/CUUR0000SETB01',
    'US All Grades Conventional Gas': 'FRED/GASALLCOVW',
    'US Premium Conventional Gas': 'FRED/GASPRMCOVW',
    'NYMEX Natural Gas Futures': 'CHRIS/CME_NG1',
    'ICE UK Natural Gas Futures': 'CHRIS/ICE_M1',
    'Natural Gas (vs. Crude)': 'BRP/GAS_PRICES',
    'Germany Natural Gas': 'ODA/PNGASEU_USD',
    'Henry Hub Natural Gas': 'ODA/PNGASUS_USD',
    'Japan Natural Gas': 'ODA/PNGASJP_USD',
    'Natural Gas: Henry Hub, LA': 'FRED/GASPRICE',
    'Import (End Use): Gas-natural': 'FRED/IR10110',
    'U.S. Coals, 1949-2005': 'EPI/152',
    'US Coals by Region': 'DOE/COAL',
    'Coals': 'BRP/COAL_PRICES',
    'Coal, South African export Monthly': 'INDEXMUNDI/COMMODITY_COALSOUTHAFRICANEXPORTPRICE',
    'Coal': 'ODA/PCOALAU_USD',
    'Coal, Australia': 'WORLDBANK/WLD_COAL_AUS',
    'Coal Exports for Great Britain': 'FRED/M04111GBM318NNBR',
    'Wholesale of Coal for Essen, Germany': 'FRED/M04I1ADE00ESSM372NNBR',
    'Arabica Coffee': 'ODA/PCOFFOTM_USD',
    'Robusta Coffee': 'ODA/PCOFFROB_USD',
    'Coffee Futures': 'CHRIS/ICE_KC1',
    'Cocoa beans': 'ODA/PCOCO_USD',
    'Cocoa Futures': 'CHRIS/ICE_CC1',
    'Tobacco': 'WORLDBANK/WLD_TOBAC_US',
    'Tea': 'ODA/PTEA_USD',
    'Tea, Mombasa auctions': 'WORLDBANK/WLD_TEA_MOMBASA',
    'US Imports Sugar': 'ODA/PSUGAUSA_USD',
    'Sugar No. 11 Futures': 'CHRIS/ICE_SB1',
    'Groundnuts (Peanuts)': 'ODA/PGNUTS_USD',
    'Oranges': 'ODA/PORANG_USD',
    'Orange Juice Futures': 'CHRIS/ICE_OJ1',
    'Bananas': 'ODA/PBANSOP_USD',
    'Bananas, US': 'WORLDBANK/WLD_BANANA_US',
    'Rapeseed Oil': 'ODA/PROIL_USD',
    'Sunflower Oil': 'ODA/PSUNO_USD',
    'Olive Oil': 'ODA/POLVOIL_USD',
    'Palm Oil': 'ODA/PPOIL_USD',
    'Palmkernal oil': 'WORLDBANK/WLD_PLMKRNL_OIL',
    'Groundnut oil': 'WORLDBANK/WLD_GRNUT_OIL',
    'Hard Logs': 'ODA/PLOGSK_USD',
    'Soft Logs': 'ODA/PLOGORE_USD',
    'Copra': 'WORLDBANK/WLD_COPRA',
    'Soft Sawnwood': 'ODA/PSAWORE_USD',
    'Hard Sawnwood': 'ODA/PSAWMAL_USD',
    'Woodpulp': 'WORLDBANK/WLD_WOODPULP',
    'Plywood': 'WORLDBANK/WLD_PLYWOOD',
    'Lumber Futures': 'CHRIS/CME_LB1',
    'Rubber': 'ODA/PRUBB_USD',
    'Cotton': 'ODA/PCOTTIND_USD',
    'Cotton No. 2 Futures': 'CHRIS/ICE_CT1',
    'Urea, E. Europe, bulk': 'WORLDBANK/WLD_UREA_EE_BULK',
    'Phosphate rock Pric': 'WORLDBANK/WLD_PHOSROCK',
    'Potash (Potassium Chloride)': 'WORLDBANK/WLD_POTASH',
    'TSP': 'WORLDBANK/WLD_TSP',
    'DAP': 'WORLDBANK/WLD_DAP',
    'Fertilizers Index, 2000=100': 'WORLDBANK/WLD_IFERTILIZERS',
    'Food Index, 2000=100': 'WORLDBANK/WLD_IFOOD',
    '1 Timber Index, 2000=100': 'WORLDBANK/WLD_ITIMBER',
    'Metals and minerals Index, 2000=100': 'WORLDBANK/WLD_IMETMIN',
    'Beverages Index, 2000=100': 'WORLDBANK/WLD_IBEVERAGES',
    'Energy Index, 2000=100': 'WORLDBANK/WLD_IENERGY',
    'Non-energy commodities Index, 2000=100': 'WORLDBANK/WLD_INONFUEL',
    'Fats and oils Index, 2000=100': 'WORLDBANK/WLD_IFATS_OILS',
    'Agriculture Index, 2000=100': 'WORLDBANK/WLD_IAGRICULTURE',
    'Grains Index, 2000=100': 'WORLDBANK/WLD_IGRAINS',
    'Raw materials Index, 2000=100': 'WORLDBANK/WLD_IRAW_MATERIAL',
    '2 Oth raw materials Index, 2000=100': 'WORLDBANK/WLD_IOTHERRAWMAT',
    'Other food Index, 2000=100': 'WORLDBANK/WLD_IOTHERFOOD'
}

module.exports = varNames
